import type { RegisterPreference } from '../grammar/presets';
import type { StoryForm } from '../reading/reading';
import type { SnapshotId } from '../shared/ids';
import { err, ok, type Result } from '../shared/result';

export const STORY_SENTENCE_COUNTS = [5, 15, 30, 50, 100, 200, 400, 800] as const;
export const MIN_STORY_SENTENCES = STORY_SENTENCE_COUNTS[0];
export const MAX_STORY_SENTENCES = STORY_SENTENCE_COUNTS[STORY_SENTENCE_COUNTS.length - 1];
export const DEFAULT_STORY_SENTENCES = 15;
/** At and above this count, models become notably less reliable at obeying constraints. */
export const STORY_LENGTH_RELIABILITY_WARNING_SENTENCES = 100;
/** Maximum generated by one structured model response. */
export const MAX_STORY_SEGMENT_SENTENCES = 50;

export interface StorySegmentPlan {
  readonly index: number;
  readonly sentenceCount: number;
}

export interface StoryBlueprintSegment extends StorySegmentPlan {
  readonly beatEn: string;
}

export interface StoryBlueprint {
  readonly titleJa: string;
  readonly segments: readonly StoryBlueprintSegment[];
}

export interface StorySegmentRequest {
  readonly original: StoryGenerationRequest;
  readonly blueprint: StoryBlueprint;
  readonly segment: StoryBlueprintSegment;
  readonly continuitySummaryEn: string;
  readonly precedingSentencesJa: readonly string[];
}

export interface StorySegmentCandidate {
  readonly sentences: readonly CandidateSentence[];
  /** Compact cumulative state for the next segment; never shown to the learner. */
  readonly continuitySummaryEn: string;
}

export function normalizeStorySentenceCount(value: number): number {
  if (!Number.isFinite(value)) {
    return DEFAULT_STORY_SENTENCES;
  }
  return STORY_SENTENCE_COUNTS.reduce((closest, candidate) =>
    Math.abs(candidate - value) < Math.abs(closest - value) ? candidate : closest,
  );
}

/** Divides a requested total into deterministic contiguous model-sized segments. */
export function planStorySegments(
  sentenceCount: number,
  maximum: number = MAX_STORY_SEGMENT_SENTENCES,
): readonly StorySegmentPlan[] {
  if (!Number.isInteger(sentenceCount) || sentenceCount < 1) {
    return [];
  }
  if (!Number.isInteger(maximum) || maximum < 1) {
    throw new Error('planStorySegments: maximum must be a positive integer');
  }
  const plans: StorySegmentPlan[] = [];
  let remaining = sentenceCount;
  while (remaining > 0) {
    plans.push({ index: plans.length, sentenceCount: Math.min(maximum, remaining) });
    remaining -= plans[plans.length - 1].sentenceCount;
  }
  return plans;
}

/** A broad format label retained in saved-story metadata and prompt wording. */
export function storyFormForSentenceCount(sentenceCount: number): StoryForm {
  if (sentenceCount <= 5) {
    return 'micro';
  }
  if (sentenceCount <= 20) {
    return 'short';
  }
  if (sentenceCount <= 30) {
    return 'medium';
  }
  return 'long';
}

export const MAX_PREMISE_LENGTH = 1_000;
export const MAX_SPECIAL_INSTRUCTIONS_LENGTH = 1_000;

/**
 * Everything one story generation is judged and reproduced against.
 *
 * The structural baseline arrives as plain forms rather than as rule objects:
 * the enumerated rule catalog was removed in ADR 0014, and the model only needs
 * to be told which function words stay available when the allowlist otherwise
 * forbids everything outside the learner's reviewed vocabulary. See ADR 0019.
 */
export interface StoryGenerationRequest {
  readonly form: StoryForm;
  /** A prompt target, not a local acceptance constraint. */
  readonly requestedSentenceCount: number;
  readonly premise: string;
  readonly specialInstructions?: string;
  /** Canonical expressions the story may use. The local validation authority. */
  readonly allowedVocabulary: readonly string[];
  /** Inspiration only; never required, never displayed. */
  readonly suggestedVocabulary: readonly string[];
  /** Function words that count as readable regardless of the allowlist. */
  readonly structuralBaseline: readonly string[];
  readonly grammarGuidance: string;
  readonly registerPreference: RegisterPreference;
  readonly snapshotId: SnapshotId;
  readonly grammarProfileHash: string;
  readonly promptVersion: string;
}

/** One sentence exactly as the model returned it, before any local work. */
export interface CandidateSentence {
  readonly index: number;
  readonly textJa: string;
}

export interface StoryCandidate {
  readonly titleJa: string;
  readonly sentences: readonly CandidateSentence[];
}

export type StoryInputIssueCode =
  'premise-empty' | 'premise-too-long' | 'special-instructions-too-long';

export interface StoryInputIssue {
  readonly code: StoryInputIssueCode;
  readonly field: 'premise' | 'specialInstructions';
  readonly message: string;
}

/** The learner's own text, trimmed and proven to fit the documented limits. */
export interface ValidatedStoryInput {
  readonly premise: string;
  readonly specialInstructions?: string;
}

export interface StoryInputDraft {
  readonly premise: string;
  readonly specialInstructions?: string;
}

/**
 * Length in Unicode code points.
 *
 * The limit is stated to the learner in characters, so a rare kanji or an emoji
 * must count once rather than twice. Code points, not grapheme clusters: the
 * limit is a size guard on what is sent, not a typographic measurement, and a
 * locale-aware segmenter would make the same number depend on the locale.
 */
export function countCodePoints(text: string): number {
  let count = 0;
  for (const _character of text) {
    count += 1;
  }
  return count;
}

/**
 * Checks the two free-text fields before anything is spent.
 *
 * Length is measured in Unicode code points rather than UTF-16 units, because
 * the limit is stated to the learner in characters and an emoji or a rare kanji
 * would otherwise silently count twice.
 */
export function validateStoryInput(
  draft: StoryInputDraft,
): Result<ValidatedStoryInput, readonly StoryInputIssue[]> {
  const issues: StoryInputIssue[] = [];
  const premise = draft.premise.trim();
  const instructions = draft.specialInstructions?.trim() ?? '';

  if (premise === '') {
    issues.push({
      code: 'premise-empty',
      field: 'premise',
      message: 'Describe what the story should be about.',
    });
  } else if (countCodePoints(premise) > MAX_PREMISE_LENGTH) {
    issues.push({
      code: 'premise-too-long',
      field: 'premise',
      message: `Shorten the premise to ${String(MAX_PREMISE_LENGTH)} characters or fewer.`,
    });
  }

  if (countCodePoints(instructions) > MAX_SPECIAL_INSTRUCTIONS_LENGTH) {
    issues.push({
      code: 'special-instructions-too-long',
      field: 'specialInstructions',
      message: `Shorten the special instructions to ${String(
        MAX_SPECIAL_INSTRUCTIONS_LENGTH,
      )} characters or fewer.`,
    });
  }

  if (issues.length > 0) {
    return err(issues);
  }
  return ok({
    premise,
    ...(instructions === '' ? {} : { specialInstructions: instructions }),
  });
}
