import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
  signal,
  viewChild,
  type ElementRef,
} from '@angular/core';

/** How far a sheet must be dragged down before letting go dismisses it. */
const DISMISS_DISTANCE_PX = 80;
/** A flick this fast sends the sheet away however short the drag was. */
const FLING_VELOCITY_PX_PER_MS = 0.5;
/** Below this the finger wobbled on a press; there is no flick to read. */
const FLING_DISTANCE_PX = 16;
/** Only the tail of the gesture is measured, so an earlier pause cannot flatten a flick. */
const VELOCITY_WINDOW_MS = 100;
/** A finger that rested this long before letting go has settled, whatever it did before. */
const SETTLED_MS = 120;

interface DragSample {
  readonly y: number;
  readonly time: number;
}

/**
 * The grab handle that dismisses a docked bottom sheet.
 *
 * A docked sheet carries no close control, so this handle is both the
 * affordance and the way out. It owns the gesture — pointer capture, the drag
 * distance, and the release — and reports the distance so the surface above it
 * can follow the finger. Every sheet shares it, whether the surface is a native
 * popover or a CDK dialog.
 *
 * Letting go is read the way Android reads it: a drag past the threshold or a
 * downward flick sends the sheet away, and anything less springs back. Speed
 * matters because a short flick is how a sheet is usually dismissed on a phone,
 * and waiting for it to travel 80px first makes the gesture feel deaf.
 */
@Component({
  selector: 'mn-sheet-handle',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button
      #button
      type="button"
      class="handle"
      [attr.aria-label]="label()"
      (pointerdown)="onDragStart($event)"
      (pointermove)="onDragMove($event)"
      (pointerup)="onDragEnd($event)"
      (pointercancel)="onDragEnd()"
      (click)="onClick()"
    >
      <span class="grip" aria-hidden="true"></span>
    </button>
  `,
  styles: `
    :host {
      /* How far the handle reaches past its surface's padding, so the grip
         spans the full sheet rather than the text column inside it. */
      --mn-sheet-handle-bleed: 0px;

      position: sticky;
      top: 0;
      z-index: 2;
      display: block;
      width: calc(100% + 2 * var(--mn-sheet-handle-bleed));
      margin-inline: calc(-1 * var(--mn-sheet-handle-bleed));
      background: var(--surface-panel);
    }

    .handle {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 100%;
      min-height: var(--touch-target);
      padding: 0;
      border: 0;
      background: none;
      cursor: grab;
      touch-action: none;
    }

    .grip {
      display: block;
      width: 2.5rem;
      height: 4px;
      border-radius: var(--radius-pill);
      background: var(--border-strong);
      opacity: 0.6;
    }

    .handle:active .grip {
      opacity: 1;
    }
  `,
})
export class SheetHandleComponent {
  /** Names the action for keyboard and assistive technology users. */
  readonly label = input('Close');
  /** Emitted when the handle answers a dismissal gesture. */
  readonly dismissed = output<void>();

  private readonly button = viewChild<ElementRef<HTMLButtonElement>>('button');
  private readonly offsetSignal = signal(0);

  /** How far the sheet has been dragged down, for the surface to follow. */
  readonly offset = this.offsetSignal.asReadonly();
  readonly dragging = computed(() => this.offsetSignal() > 0);

  private dragStartY: number | null = null;
  /** Set by a drag so the click generated by its release is not a second close. */
  private dragged = false;
  /** The tail of the gesture, from which the release speed is read. */
  private samples: DragSample[] = [];

  focus(): void {
    this.button()?.nativeElement.focus({ preventScroll: true });
  }

  protected onDragStart(event: PointerEvent): void {
    this.dragStartY = event.clientY;
    this.samples = [];
    this.track(event);
    const target = event.currentTarget as Element;
    target.setPointerCapture(event.pointerId);
  }

  protected onDragMove(event: PointerEvent): void {
    if (this.dragStartY === null) {
      return;
    }
    // Downwards only: lifting a docked sheet would leave a gap below it.
    const offset = Math.max(0, event.clientY - this.dragStartY);
    if (offset > 0) {
      this.dragged = true;
    }
    this.track(event);
    this.offsetSignal.set(offset);
  }

  protected onDragEnd(event?: PointerEvent): void {
    const offset = this.offsetSignal();
    const dismissed = offset >= DISMISS_DISTANCE_PX || this.flung(offset, event);
    this.dragStartY = null;
    this.samples = [];
    // The surface takes over here: it carries on from where the finger left the
    // sheet, either back to the docked edge or down off it.
    this.offsetSignal.set(0);
    if (dismissed) {
      this.dismissed.emit();
    }
  }

  private track(event: PointerEvent): void {
    this.samples.push({ y: event.clientY, time: event.timeStamp });
    while (this.samples.length > 2 && event.timeStamp - this.samples[0].time > VELOCITY_WINDOW_MS) {
      this.samples.shift();
    }
  }

  /** Whether the release was a downward flick rather than a finger coming to rest. */
  private flung(offset: number, event: PointerEvent | undefined): boolean {
    const first = this.samples.at(0);
    const last = this.samples.at(-1);
    if (event === undefined || first === undefined || last === undefined) {
      return false;
    }
    const measured = last.time - first.time;
    if (offset < FLING_DISTANCE_PX || measured <= 0 || event.timeStamp - last.time > SETTLED_MS) {
      return false;
    }
    return (last.y - first.y) / measured >= FLING_VELOCITY_PX_PER_MS;
  }

  /** A plain handle press closes; a short drag springs back and stays open. */
  protected onClick(): void {
    if (this.dragged) {
      this.dragged = false;
      return;
    }
    this.dismissed.emit();
  }
}
