import {
  LucideArrowDown,
  LucideArrowLeft,
  LucideArrowUp,
  LucideAudioLines,
  LucideBookOpen,
  LucideChartNoAxesColumnIncreasing,
  LucideCheck,
  LucideChevronDown,
  LucideChevronRight,
  LucideChevronUp,
  LucideCircleAlert,
  LucideCircleCheck,
  LucideCopy,
  LucideCornerRightUp,
  LucideDatabase,
  LucideEllipsisVertical,
  LucidePencil,
  LucideFileText,
  LucideGitFork,
  LucideCircleQuestionMark,
  LucideHouse,
  type LucideIcon,
  LucideInfo,
  LucideLanguages,
  LucideLibrary,
  LucideList,
  LucideListChecks,
  LucideListFilter,
  LucideListStart,
  LucideMenu,
  LucideMerge,
  LucidePause,
  LucidePlay,
  LucidePlus,
  LucideRefreshCw,
  LucideRotateCcw,
  LucideScissors,
  LucideSkipBack,
  LucideSkipForward,
  LucideSquare,
  LucideStepForward,
  LucideSearch,
  LucideSettings,
  LucideSlidersHorizontal,
  LucideSparkles,
  LucideSpellCheck,
  LucideTrash2,
  LucideUpload,
  LucideX,
} from '@lucide/angular';

/**
 * Semantic icon names used by the application, mapped to the bundled Lucide
 * set. Features refer to intent (`delete`, `back`) rather than to a specific
 * icon library, so the set can be replaced in one place.
 */
export const ICON_SET = {
  home: LucideHouse,
  library: LucideLibrary,
  add: LucidePlus,
  generate: LucideSparkles,
  vocabulary: LucideBookOpen,
  grammar: LucideSpellCheck,
  translate: LucideLanguages,
  settings: LucideSettings,
  help: LucideCircleQuestionMark,
  github: LucideGitFork,
  more: LucideMenu,
  close: LucideX,
  back: LucideArrowLeft,
  warning: LucideCircleAlert,
  check: LucideCheck,
  copy: LucideCopy,
  delete: LucideTrash2,
  rename: LucidePencil,
  file: LucideFileText,
  search: LucideSearch,
  overflow: LucideEllipsisVertical,
  split: LucideScissors,
  merge: LucideMerge,
  'chevron-up': LucideChevronUp,
  'chevron-down': LucideChevronDown,
  'chevron-right': LucideChevronRight,
  upload: LucideUpload,
  info: LucideInfo,
  aids: LucideSlidersHorizontal,
  audio: LucideAudioLines,
  play: LucidePlay,
  pause: LucidePause,
  stop: LucideSquare,
  'skip-forward': LucideSkipForward,
  'skip-back': LucideSkipBack,
  step: LucideStepForward,
  retry: LucideRotateCcw,
  'sentence-start': LucideListStart,
  'sentence-details': LucideCornerRightUp,
  prepare: LucideListChecks,
  'anki-source': LucideDatabase,
  'word-list': LucideList,
  'reading-level': LucideChartNoAxesColumnIncreasing,
  filter: LucideListFilter,
  sync: LucideRefreshCw,
  synced: LucideCircleCheck,
  'sort-descending': LucideArrowDown,
  'sort-ascending': LucideArrowUp,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICON_SET;
