import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  input,
  output,
  signal,
  viewChild,
} from '@angular/core';
import { ViewportService } from '../../core/platform/viewport.service';

/** How far a sheet must be dragged down before letting go dismisses it. */
const DISMISS_DISTANCE_PX = 80;

interface NativePopoverElement extends Omit<HTMLElement, 'hidePopover' | 'showPopover'> {
  readonly hidePopover?: () => void;
  readonly showPopover?: () => void;
}

/**
 * Shared native-popover surface for panels that become bottom sheets on touch.
 *
 * The native popover stays on the host so it can light-dismiss, survive the
 * file chooser, and keep its accessible relationship with its trigger. This
 * component owns the part that used to drift between panels: the mobile grab
 * handle, pointer capture, drag transform, and dismissal threshold.
 */
@Component({
  selector: 'mn-sheet-popover',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class.is-sheet]': 'isMobile()',
    '[class.is-dragging]': 'dragOffset() > 0',
    '[style.transform]': 'dragTransform()',
    '[style.position-anchor]': 'anchorName()',
    '[attr.data-modal]': "modal() ? '' : null",
  },
  template: `
    @if (isMobile()) {
      <button
        #handle
        type="button"
        class="handle"
        [attr.aria-label]="closeLabel()"
        (pointerdown)="onDragStart($event)"
        (pointermove)="onDragMove($event)"
        (pointerup)="onDragEnd()"
        (pointercancel)="onDragEnd()"
        (click)="onHandleClick()"
      >
        <span class="grip" aria-hidden="true"></span>
      </button>
    }
    <ng-content />
  `,
  styles: `
    :host {
      position: fixed;
      z-index: 10;
      inset: auto;
      position-area: bottom span-left;
      display: grid;
      gap: var(--space-3);
      box-sizing: border-box;
      width: min(25rem, calc(100vw - 2 * var(--space-4)));
      max-height: calc(100dvh - 6rem);
      margin: var(--space-2) 0 0;
      padding: var(--space-4);
      overflow-y: auto;
      overscroll-behavior: contain;
      border: 1px solid var(--border-subtle);
      border-radius: var(--radius-sheet);
      background: var(--surface-panel);
      color: var(--text-primary);
      box-shadow: var(--shadow-overlay);
      transition: transform var(--motion-medium) cubic-bezier(0.2, 0, 0, 1);
    }

    :host(:not(:popover-open)) {
      display: none;
    }

    :host(.is-sheet) {
      inset: auto 0 0;
      width: 100%;
      max-width: none;
      max-height: calc(100dvh - var(--space-4));
      margin: 0;
      padding: 0 var(--space-4) max(var(--space-4), env(safe-area-inset-bottom));
      overflow-y: auto;
      border-width: 1px 0 0;
      border-radius: var(--radius-sheet) var(--radius-sheet) 0 0;
    }

    :host([data-modal])::backdrop {
      background: var(--backdrop-scrim);
    }

    :host(.is-dragging) {
      transition: none;
    }

    .handle {
      position: sticky;
      top: 0;
      z-index: 2;
      display: flex;
      align-items: center;
      justify-content: center;
      width: calc(100% + 2 * var(--space-4));
      min-height: var(--touch-target);
      margin-inline: calc(-1 * var(--space-4));
      padding: 0;
      border: 0;
      background: var(--surface-panel);
      cursor: grab;
      touch-action: none;
    }

    .grip {
      display: block;
      width: 2.5rem;
      height: 4px;
      border-radius: var(--radius-pill);
      background: var(--border-strong);
      opacity: 0.6;
    }

    .handle:active .grip {
      opacity: 1;
    }

    @media (prefers-reduced-motion: reduce) {
      :host {
        transition: none;
      }
    }
  `,
})
export class SheetPopoverComponent {
  /** The anchor name used by the desktop popover placement rule. */
  readonly anchorName = input.required<string>();
  /** Names the action for keyboard and assistive technology users. */
  readonly closeLabel = input('Close');
  /** Adds the native popover backdrop for a modal sheet. */
  readonly modal = input(false);
  /** Emitted when the handle answers a dismissal gesture. */
  readonly closed = output<void>();

  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly viewport = inject(ViewportService);
  private readonly handle = viewChild<ElementRef<HTMLButtonElement>>('handle');

  protected readonly isMobile = this.viewport.isMobile;
  private readonly dragOffsetSignal = signal(0);
  protected readonly dragOffset = this.dragOffsetSignal.asReadonly();
  protected readonly dragTransform = computed(() => {
    const offset = this.dragOffsetSignal();
    return offset === 0 ? null : `translateY(${String(offset)}px)`;
  });

  private dragStartY: number | null = null;
  /** Set by a drag so the click generated by its release is not a second close. */
  private dragged = false;

  /** The native popover element for the owning feature's open/close lifecycle. */
  element(): HTMLElement {
    return this.host.nativeElement;
  }

  isOpen(): boolean {
    return this.host.nativeElement.matches(':popover-open');
  }

  show(): void {
    (this.host.nativeElement as NativePopoverElement).showPopover?.();
  }

  hide(): void {
    (this.host.nativeElement as NativePopoverElement).hidePopover?.();
  }

  focusHandle(): void {
    this.handle()?.nativeElement.focus({ preventScroll: true });
  }

  protected onDragStart(event: PointerEvent): void {
    this.dragStartY = event.clientY;
    const target = event.currentTarget as Element;
    target.setPointerCapture(event.pointerId);
  }

  protected onDragMove(event: PointerEvent): void {
    if (this.dragStartY === null) {
      return;
    }
    // Downwards only: lifting a docked sheet would leave a gap below it.
    const offset = Math.max(0, event.clientY - this.dragStartY);
    if (offset > 0) {
      this.dragged = true;
    }
    this.dragOffsetSignal.set(offset);
  }

  protected onDragEnd(): void {
    const dismissed = this.dragOffsetSignal() >= DISMISS_DISTANCE_PX;
    this.dragStartY = null;
    this.dragOffsetSignal.set(0);
    if (dismissed) {
      this.closed.emit();
    }
  }

  /** A plain handle press closes; a short drag springs back and stays open. */
  protected onHandleClick(): void {
    if (this.dragged) {
      this.dragged = false;
      return;
    }
    this.closed.emit();
  }
}
