import {
  LucideArrowLeft,
  LucideAudioLines,
  LucideBookOpen,
  LucideCheck,
  LucideChevronDown,
  LucideChevronRight,
  LucideChevronUp,
  LucideCircleAlert,
  LucideCopy,
  LucideEllipsisVertical,
  LucideFileText,
  type LucideIcon,
  LucideInfo,
  LucideLanguages,
  LucideLibrary,
  LucideListChecks,
  LucideListStart,
  LucideMenu,
  LucideMerge,
  LucidePause,
  LucidePlay,
  LucidePlus,
  LucideRotateCcw,
  LucideScissors,
  LucideSkipBack,
  LucideSkipForward,
  LucideSquare,
  LucideStepForward,
  LucideSearch,
  LucideSettings,
  LucideSlidersHorizontal,
  LucideSparkles,
  LucideSpellCheck,
  LucideTrash2,
  LucideUpload,
  LucideX,
} from '@lucide/angular';

/**
 * Semantic icon names used by the application, mapped to the bundled Lucide
 * set. Features refer to intent (`delete`, `back`) rather than to a specific
 * icon library, so the set can be replaced in one place.
 */
export const ICON_SET = {
  library: LucideLibrary,
  add: LucidePlus,
  generate: LucideSparkles,
  vocabulary: LucideBookOpen,
  grammar: LucideSpellCheck,
  translate: LucideLanguages,
  settings: LucideSettings,
  more: LucideMenu,
  close: LucideX,
  back: LucideArrowLeft,
  warning: LucideCircleAlert,
  check: LucideCheck,
  copy: LucideCopy,
  delete: LucideTrash2,
  file: LucideFileText,
  search: LucideSearch,
  overflow: LucideEllipsisVertical,
  split: LucideScissors,
  merge: LucideMerge,
  'chevron-up': LucideChevronUp,
  'chevron-down': LucideChevronDown,
  'chevron-right': LucideChevronRight,
  upload: LucideUpload,
  info: LucideInfo,
  aids: LucideSlidersHorizontal,
  audio: LucideAudioLines,
  play: LucidePlay,
  pause: LucidePause,
  stop: LucideSquare,
  'skip-forward': LucideSkipForward,
  'skip-back': LucideSkipBack,
  step: LucideStepForward,
  retry: LucideRotateCcw,
  'sentence-start': LucideListStart,
  prepare: LucideListChecks,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICON_SET;
